# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("ALLOW", "ALLOW"),
                            ("THROTTLE", "THROTTLE"),
                            ("REQUIRE_APPROVAL", "REQUIRE_APPROVAL"),
                            ("DENY", "DENY"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "risk_class",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "risk_components",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canon §9.2 — svaki sabirak posebno, radi objašnjivosti.",
                    ),
                ),
                (
                    "matched_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"key": "…", "version": 3, "effect": "…"}]',
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("reason", models.TextField()),
                (
                    "approval_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("A3", "A3"),
                            ("A4", "A4"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("fail_closed", models.BooleanField(default=False)),
                ("evaluator_version", models.CharField(blank=True, max_length=40)),
                ("context_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                (
                    "eval_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="orchestration.action",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_decisions",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "policy_decision",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                (
                    "approval_class",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("A3", "A3"),
                            ("A4", "A4"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("APPROVED_WITH_CHANGES", "APPROVED_WITH_CHANGES"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELLED", "CANCELLED"),
                            ("REVOKED", "REVOKED"),
                        ],
                        default=common.enums.ApprovalStatus["PENDING"],
                        max_length=24,
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("requested_by", models.CharField(max_length=120)),
                ("assigned_to", models.CharField(blank=True, max_length=180)),
                ("reason", models.TextField()),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Canon §15.2 — TTL po klasi; prenosi se kao approval_expires_at."
                    ),
                ),
                (
                    "expiry_effect",
                    models.CharField(
                        help_text="Canon §15.2 — APPROVAL_EXPIRY_EFFECT.", max_length=40
                    ),
                ),
                ("decided_by", models.CharField(blank=True, max_length=180)),
                (
                    "decided_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("viewer", "viewer"),
                            ("operator", "operator"),
                            ("persona_manager", "persona_manager"),
                            ("trust_safety", "trust_safety"),
                            ("runtime_admin", "runtime_admin"),
                            ("system_admin", "system_admin"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="orchestration.action",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to="policy.policydecision",
                    ),
                ),
            ],
            options={
                "db_table": "policy_approval_request",
            },
        ),
        migrations.CreateModel(
            name="PolicyIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=24, unique=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("SEV1", "SEV1"),
                            ("SEV2", "SEV2"),
                            ("SEV3", "SEV3"),
                            ("SEV4", "SEV4"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("ACKNOWLEDGED", "ACKNOWLEDGED"),
                            ("MITIGATED", "MITIGATED"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default=common.enums.IncidentStatus["OPEN"],
                        max_length=24,
                    ),
                ),
                ("incident_kind", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                ("detected_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("mitigated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("owner", models.CharField(blank=True, max_length=180)),
                ("timeline", models.JSONField(blank=True, default=list)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="orchestration.action",
                    ),
                ),
                (
                    "channel_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="channels.channelaccount",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="policy.policydecision",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "policy_incident",
            },
        ),
        migrations.CreateModel(
            name="KillSwitch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "GLOBAL"),
                            ("CHANNEL", "CHANNEL"),
                            ("PERSONA", "PERSONA"),
                            ("CAPABILITY", "CAPABILITY"),
                            ("ACCOUNT", "ACCOUNT"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_ref",
                    models.CharField(
                        blank=True,
                        help_text="Prazno za GLOBAL; inače persona/kanal/capability/nalog.",
                        max_length=220,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("reason", models.TextField()),
                ("activated_by", models.CharField(max_length=180)),
                ("activated_at", models.DateTimeField()),
                ("released_by", models.CharField(blank=True, max_length=180)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_workers", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stop_latency_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Do poslednjeg zaustavljenog worker-a.",
                        null=True,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kill_switches",
                        to="policy.policyincident",
                    ),
                ),
            ],
            options={
                "db_table": "policy_kill_switch",
            },
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=180)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "global"),
                            ("channel", "channel"),
                            ("persona", "persona"),
                            ("action", "action"),
                            ("cohort", "cohort"),
                            ("capability", "capability"),
                            ("account", "account"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEBSITE", "WEBSITE"),
                            ("NEWSLETTER", "NEWSLETTER"),
                            ("EMAIL", "EMAIL"),
                            ("LINKEDIN", "LINKEDIN"),
                            ("INSTAGRAM", "INSTAGRAM"),
                            ("FACEBOOK", "FACEBOOK"),
                            ("X", "X"),
                            ("TIKTOK", "TIKTOK"),
                            ("YOUTUBE", "YOUTUBE"),
                            ("SANDBOX", "SANDBOX"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("action_type", models.CharField(blank=True, max_length=64)),
                ("capability", models.CharField(blank=True, max_length=64)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("ALLOW", "ALLOW"),
                            ("THROTTLE", "THROTTLE"),
                            ("REQUIRE_APPROVAL", "REQUIRE_APPROVAL"),
                            ("DENY", "DENY"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "approval_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("A3", "A3"),
                            ("A4", "A4"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "condition_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="DSL uslov; prazan objekat = uvek tačno.",
                    ),
                ),
                (
                    "rate_limit_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Canon §9.3 — pilot limiti."
                    ),
                ),
                (
                    "risk_delta",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Doprinos formuli iz §9.2; težine su u policy/risk_weights.yaml.",
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_hard_prohibition",
                    models.BooleanField(
                        default=False,
                        help_text="Canon §9.4 — tvrde zabrane nisu pravila koja se mogu isključiti. Red sa True postoji radi traga i reason_code-a, ne radi konfiguracije.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("policy_ext", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "policy_rule",
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "effective_from"],
                        name="policy_rule_is_enab_7c8dc2_idx",
                    ),
                    models.Index(
                        fields=["channel_type", "action_type"],
                        name="policy_rule_channel_1f69f1_idx",
                    ),
                    models.Index(
                        fields=["scope", "is_enabled"],
                        name="policy_rule_scope_501d83_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="policy_rule_unique_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="policy_rule_period_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("effect", "REQUIRE_APPROVAL"), _negated=True),
                            ("approval_class__isnull", False),
                            _connector="OR",
                        ),
                        name="policy_rule_approval_needs_class",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="policydecision",
            name="decisive_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="policy.policyrule",
            ),
        ),
        migrations.CreateModel(
            name="TrustState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capability", models.CharField(max_length=64)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L0", "L0"),
                            ("L1", "L1"),
                            ("L2", "L2"),
                            ("L3", "L3"),
                            ("L4", "L4"),
                        ],
                        default=common.enums.TrustLevel["L0"],
                        max_length=4,
                    ),
                ),
                ("granted_at", models.DateTimeField()),
                ("evidence_ref", models.CharField(blank=True, max_length=512)),
                ("auto_downgrade_count", models.PositiveSmallIntegerField(default=0)),
                ("last_downgrade_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "last_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_states",
                        to="policy.policyincident",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_states",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "policy_trust_state",
            },
        ),
        migrations.CreateModel(
            name="CapabilityGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capability", models.CharField(max_length=64)),
                (
                    "min_trust_level",
                    models.CharField(
                        choices=[
                            ("L0", "L0"),
                            ("L1", "L1"),
                            ("L2", "L2"),
                            ("L3", "L3"),
                            ("L4", "L4"),
                        ],
                        max_length=4,
                    ),
                ),
                ("granted_by", models.CharField(max_length=180)),
                ("granted_at", models.DateTimeField()),
                ("evidence_ref", models.CharField(blank=True, max_length=512)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capability_grants",
                        to="policy.approvalrequest",
                    ),
                ),
                (
                    "channel_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = važi za sve naloge persone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_grants",
                        to="channels.channelaccount",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_grants",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "policy_capability_grant",
                "indexes": [
                    models.Index(
                        fields=["persona", "capability"],
                        name="policy_capa_persona_1aaed2_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="policy_capa_expires_797a1a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("persona", "capability", "channel_account"),
                        name="capability_grant_unique_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_trust_level__in", ("L0", "L1", "L2"))),
                        name="capability_grant_trust_assignable",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["status", "created_at"], name="policy_appr_status_041996_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["action", "status"], name="policy_appr_action__db87a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["expires_at"], name="policy_appr_expires_f33d3c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            (
                                "APPROVED",
                                "APPROVED_WITH_CHANGES",
                                "REJECTED",
                                "REVOKED",
                            ),
                        ),
                        _negated=True,
                    ),
                    ("decided_at__isnull", False),
                    _connector="OR",
                ),
                name="approval_decided_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            (
                                "APPROVED",
                                "APPROVED_WITH_CHANGES",
                                "REJECTED",
                                "REVOKED",
                            ),
                        ),
                        _negated=True,
                    ),
                    models.Q(("decided_by", ""), _negated=True),
                    _connector="OR",
                ),
                name="approval_decided_has_decider",
            ),
        ),
        migrations.AddIndex(
            model_name="policyincident",
            index=models.Index(
                fields=["status", "severity", "detected_at"],
                name="policy_inci_status_83ef10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policyincident",
            index=models.Index(
                fields=["persona", "detected_at"], name="policy_inci_persona_1d1551_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyincident",
            constraint=models.CheckConstraint(
                condition=models.Q(("detected_at__gte", models.F("occurred_at"))),
                name="incident_detected_after_occurred",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyincident",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "CLOSED"), _negated=True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="incident_closed_has_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="killswitch",
            index=models.Index(
                fields=["is_active", "scope"], name="policy_kill_is_acti_71081a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="killswitch",
            index=models.Index(
                fields=["activated_at"], name="policy_kill_activat_2aa42b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="killswitch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("scope", "target_ref"),
                name="kill_switch_unique_active_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="killswitch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "GLOBAL"), _negated=True),
                    ("target_ref", ""),
                    _connector="OR",
                ),
                name="kill_switch_global_has_no_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="killswitch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_active", True), ("released_at__isnull", True)),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="kill_switch_active_not_released",
            ),
        ),
        migrations.AddIndex(
            model_name="policydecision",
            index=models.Index(
                fields=["action", "evaluated_at"], name="policy_deci_action__c53ef4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policydecision",
            index=models.Index(
                fields=["effect", "evaluated_at"], name="policy_deci_effect_4e25e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policydecision",
            index=models.Index(
                fields=["persona", "evaluated_at"],
                name="policy_deci_persona_608a27_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="policydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("risk_score__gte", 0), ("risk_score__lte", 100)),
                name="policy_decision_risk_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="policydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect", "REQUIRE_APPROVAL"), _negated=True),
                    ("approval_class__isnull", False),
                    _connector="OR",
                ),
                name="policy_decision_approval_needs_class",
            ),
        ),
        migrations.AddIndex(
            model_name="truststate",
            index=models.Index(
                fields=["persona", "level"], name="policy_trus_persona_9a7049_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="truststate",
            constraint=models.UniqueConstraint(
                fields=("persona", "capability"), name="trust_state_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="truststate",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__in", ("L0", "L1", "L2"))),
                name="trust_state_level_assignable",
            ),
        ),
    ]
