# Generated by Django 5.2.17 on 2026-09-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policydecision",
            name="constraints",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="policydecision",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Posle ovoga odluka ne važi i gateway traži novu evaluaciju.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policydecision",
            name="obligations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Šta gateway mora da proveri pre izvršenja.",
            ),
        ),
        migrations.AddField(
            model_name="policydecision",
            name="policy_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="policydecision",
            name="reason_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Svi razlozi; prvi je odlučujući (`reason_code`).",
            ),
        ),
    ]
