# Generated by Django 5.2.17 on 2026-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0002_f11_org_and_dossier"),
        ("policy", "0002_f5_policy_decision"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="truststate",
            name="trust_state_unique_pair",
        ),
        migrations.AddField(
            model_name="truststate",
            name="scope",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddConstraint(
            model_name="truststate",
            constraint=models.UniqueConstraint(
                fields=("persona", "capability", "scope"),
                name="trust_state_unique_pair",
            ),
        ),
    ]
