# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("behaviour", "0001_initial"),
        ("personas", "0001_initial"),
        ("visuals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("post", "post"),
                            ("article", "article"),
                            ("newsletter", "newsletter"),
                            ("comment", "comment"),
                            ("reply", "reply"),
                            ("video_script", "video_script"),
                            ("thread", "thread"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=220)),
                ("body", models.TextField()),
                ("language", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("IN_REVIEW", "IN_REVIEW"),
                            ("APPROVED", "APPROVED"),
                            ("SCHEDULED", "SCHEDULED"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("REJECTED", "REJECTED"),
                            ("ARCHIVED", "ARCHIVED"),
                            ("FAILED", "FAILED"),
                        ],
                        default=common.enums.ContentStatus["DRAFT"],
                        max_length=24,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_class",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default=common.enums.RiskClass["LOW"],
                        max_length=16,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Canon §15.3 — osnov odobrenja.",
                        max_length=64,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("user_provided", "user_provided"),
                            ("generated", "generated"),
                            ("inferred", "inferred"),
                        ],
                        default=common.enums.Provenance["GENERATED"],
                        max_length=24,
                    ),
                ),
                (
                    "disclosure_included",
                    models.BooleanField(
                        default=False,
                        help_text="Canon §9.4 tačka 2 — AI priroda se ne skriva.",
                    ),
                ),
                (
                    "citations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Canon §10.4 — izvori tvrdnji, radi provere.",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "content_item",
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "SCHEDULED"),
                            ("PUBLISHING", "PUBLISHING"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("FAILED", "FAILED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default=common.enums.PublicationStatus["SCHEDULED"],
                        max_length=16,
                    ),
                ),
                (
                    "provider_post_id",
                    models.CharField(blank=True, max_length=220, null=True),
                ),
                ("public_url", models.TextField(blank=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retracted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sanitizovano — bez tajni (Canon §17).",
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "db_table": "content_publication",
            },
        ),
        migrations.CreateModel(
            name="ContentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("cover", "cover"),
                            ("inline", "inline"),
                            ("gallery", "gallery"),
                            ("video", "video"),
                            ("audio", "audio"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.SmallIntegerField(default=0)),
                ("alt_text", models.CharField(blank=True, max_length=420)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_links",
                        to="visuals.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "content_asset",
            },
        ),
        migrations.CreateModel(
            name="ContentIdea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic", models.CharField(max_length=220)),
                ("angle", models.TextField(blank=True)),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("selected", "selected"),
                            ("rejected", "rejected"),
                            ("used", "used"),
                        ],
                        default=common.enums.IdeaStatus["OPEN"],
                        max_length=16,
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True,
                        help_text="Canon §16.3 — ponavljanje sadržaja < 0,20 je kapija pilota.",
                        max_length=220,
                        null=True,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_ideas",
                        to="personas.persona",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_ideas",
                        to="behaviour.worldevent",
                    ),
                ),
            ],
            options={
                "db_table": "content_idea",
            },
        ),
    ]
