# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("memory", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentidea",
            name="source_memory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_ideas",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="idea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="content.contentidea",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_items",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="contentasset",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="content.contentitem",
            ),
        ),
    ]
