# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0002_initial"),
        ("content", "0002_initial"),
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="orchestration.action",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="channel_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publications",
                to="channels.channelaccount",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="content.contentitem",
            ),
        ),
        migrations.AddIndex(
            model_name="contentidea",
            index=models.Index(
                fields=["persona", "status", "priority"],
                name="content_ide_persona_4afa8e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentidea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key__isnull", False)),
                fields=("persona", "dedupe_key"),
                name="content_idea_unique_dedupe",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["persona", "status", "scheduled_for"],
                name="content_ite_persona_800d01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["risk_class", "status"], name="content_ite_risk_cl_74fd9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["content_hash"], name="content_ite_content_0b49ec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("risk_score__gte", 0), ("risk_score__lte", 100)),
                name="content_item_risk_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "SCHEDULED"), _negated=True),
                    ("scheduled_for__isnull", False),
                    _connector="OR",
                ),
                name="content_item_scheduled_has_time",
            ),
        ),
        migrations.AddIndex(
            model_name="contentasset",
            index=models.Index(
                fields=["content", "position"], name="content_ass_content_aebc9d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.UniqueConstraint(
                fields=("content", "asset", "role"), name="content_asset_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.UniqueConstraint(
                fields=("content", "role", "position"),
                name="content_asset_unique_position",
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["status", "scheduled_for"], name="content_pub_status_a63fa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["channel_account", "published_at"],
                name="content_pub_channel_8f9dd6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_post_id__isnull", False)),
                fields=("channel_account", "provider_post_id"),
                name="publication_unique_provider_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "PUBLISHED"), _negated=True),
                    ("published_at__isnull", False),
                    _connector="OR",
                ),
                name="publication_published_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "PUBLISHED"), _negated=True),
                    ("action__isnull", False),
                    _connector="OR",
                ),
                name="publication_published_has_action",
            ),
        ),
    ]
