# Generated by Django 5.2.17 on 2026-09-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_initial"),
        ("orchestration", "0003_f3_run_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_items",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="status_reason",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
