# Generated by Django 5.2.17 on 2026-09-22 11:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_f7_item_run"),
        ("orchestration", "0003_f3_run_decision"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        help_text="rejected | edited | manual", max_length=16
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Pravilo, kako ga model čita.", max_length=500
                    ),
                ),
                ("example_before", models.CharField(blank=True, max_length=300)),
                ("example_after", models.CharField(blank=True, max_length=300)),
                ("created_by", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prazno = važi za sve persone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_lessons",
                        to="personas.persona",
                    ),
                ),
                (
                    "source_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orchestration.action",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["persona", "is_active", "created_at"],
                        name="content_edi_persona_2402f0_idx",
                    )
                ],
            },
        ),
    ]
