# Generated by Django 5.2.17 on 2026-09-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_f10_editorial_lesson"),
        ("orchestration", "0003_f3_run_decision"),
        ("personas", "0002_f11_org_and_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="editoriallesson",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Popunjeno = pouka važi za sve u tom sektoru (ADR-0017).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editorial_lessons",
                to="personas.department",
            ),
        ),
        migrations.AlterField(
            model_name="editoriallesson",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                help_text="Prazno = važi za sve persone (ili za ceo sektor, ako je on popunjen).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editorial_lessons",
                to="personas.persona",
            ),
        ),
        migrations.AddIndex(
            model_name="editoriallesson",
            index=models.Index(
                fields=["department", "is_active", "created_at"],
                name="content_edi_departm_169afe_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="editoriallesson",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("persona__isnull", False),
                    ("department__isnull", False),
                    _negated=True,
                ),
                name="lesson_single_scope",
            ),
        ),
    ]
