# Generated by Django 5.2.17 on 2026-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_f11_lesson_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="pravopis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="ADR-0056 — nalazi Rečnika uz Pravopis nad ovim tekstom: `{provereno, nalazi:[{oblik, odrednica, tekst, tacke}]}`. `provereno=False` znači da Rečnik nije uvezen — to nije isto što i tekst bez primedbi.",
            ),
        ),
    ]
