# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("storage_namespace", models.CharField(max_length=220, unique=True)),
                (
                    "engine",
                    models.CharField(
                        default="playwright",
                        help_text="Canon §12.1 — samo Playwright.",
                        max_length=32,
                    ),
                ),
                ("locale", models.CharField(max_length=16)),
                ("timezone", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("active", "active"),
                            ("paused", "paused"),
                            ("quarantined", "quarantined"),
                            ("revoked", "revoked"),
                        ],
                        default=common.enums.AccountStatus["PENDING"],
                        max_length=24,
                    ),
                ),
                (
                    "allowed_domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=180),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "blocked_domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=180),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "max_session_seconds",
                    models.IntegerField(
                        default=900,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7200),
                        ],
                    ),
                ),
                ("kill_switch_enabled", models.BooleanField(default=True)),
                (
                    "auth_state",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "UNKNOWN"),
                            ("VALID", "VALID"),
                            ("EXPIRED", "EXPIRED"),
                            ("LOCKED", "LOCKED"),
                            ("NEEDS_HUMAN", "NEEDS_HUMAN"),
                        ],
                        default=common.enums.AuthState["UNKNOWN"],
                        max_length=24,
                    ),
                ),
                ("snapshot_version", models.IntegerField(default=1)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browser_profiles",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "runtime_browser_profile",
            },
        ),
        migrations.CreateModel(
            name="ReconcileTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("RESOLVED_EFFECT_PRESENT", "RESOLVED_EFFECT_PRESENT"),
                            ("RESOLVED_NO_EFFECT", "RESOLVED_NO_EFFECT"),
                            ("UNRESOLVED", "UNRESOLVED"),
                        ],
                        default=common.enums.ReconcileStatus["PENDING"],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "check_method",
                    models.CharField(
                        blank=True,
                        help_text="api_lookup/browser_verify/provider_search",
                        max_length=64,
                    ),
                ),
                ("checks", models.JSONField(blank=True, default=dict)),
                ("scheduled_for", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_ref", models.CharField(blank=True, max_length=512)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconcile_tasks",
                        to="orchestration.action",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconcile_tasks",
                        to="orchestration.actionattempt",
                    ),
                ),
            ],
            options={
                "db_table": "runtime_reconcile_task",
            },
        ),
        migrations.CreateModel(
            name="RuntimeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("browser", "browser"),
                            ("mail", "mail"),
                            ("llm", "llm"),
                            ("tool", "tool"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "is_write",
                    models.BooleanField(
                        default=False,
                        help_text="Canon §12.2 — najviše jedna write sesija po personi.",
                    ),
                ),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("CLOSED", "CLOSED"),
                            ("EXPIRED", "EXPIRED"),
                            ("ABORTED", "ABORTED"),
                        ],
                        default=common.enums.SessionStatus["OPEN"],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "heartbeat_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Canon §12.3 — otkucaj na 20 s.",
                        null=True,
                    ),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Canon §12.3 — TTL 90 s.", null=True
                    ),
                ),
                ("resource_json", models.JSONField(blank=True, default=dict)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "browser_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="runtime.browserprofile",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_sessions",
                        to="personas.persona",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_sessions",
                        to="orchestration.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "runtime_session",
            },
        ),
        migrations.CreateModel(
            name="WorkerJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_type", models.CharField(max_length=64)),
                (
                    "queue",
                    models.CharField(
                        choices=[
                            ("control", "control"),
                            ("approval", "approval"),
                            ("persona.interactive", "persona.interactive"),
                            ("persona.scheduled", "persona.scheduled"),
                            ("browser", "browser"),
                            ("mail", "mail"),
                            ("channel", "channel"),
                            ("memory", "memory"),
                            ("media", "media"),
                            ("maintenance", "maintenance"),
                            ("dead_letter", "dead_letter"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CLAIMED", "CLAIMED"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("RETRY", "RETRY"),
                            ("FAILED", "FAILED"),
                            ("DEAD", "DEAD"),
                        ],
                        default=common.enums.JobStatus["PENDING"],
                        max_length=16,
                    ),
                ),
                ("attempt", models.SmallIntegerField(default=0)),
                (
                    "max_attempts",
                    models.SmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("run_after", models.DateTimeField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sanitizovano — bez tajni (Canon §17).",
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("dead_lettered_at", models.DateTimeField(blank=True, null=True)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="orchestration.action",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="runtime.runtimesession",
                    ),
                ),
            ],
            options={
                "db_table": "runtime_worker_job",
            },
        ),
        migrations.AddIndex(
            model_name="browserprofile",
            index=models.Index(
                fields=["status", "last_used_at"], name="runtime_bro_status_a28594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="browserprofile",
            index=models.Index(
                fields=["persona", "auth_state"], name="runtime_bro_persona_b52941_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="browserprofile",
            constraint=models.UniqueConstraint(
                fields=("persona", "name"), name="browser_profile_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="browserprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("engine", "playwright")),
                name="browser_profile_engine_playwright_only",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciletask",
            index=models.Index(
                fields=["status", "scheduled_for"], name="runtime_rec_status_0adee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconciletask",
            index=models.Index(
                fields=["action"], name="runtime_rec_action__d6d733_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciletask",
            constraint=models.UniqueConstraint(
                fields=("attempt",), name="reconcile_task_unique_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciletask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            ["RESOLVED_EFFECT_PRESENT", "RESOLVED_NO_EFFECT"],
                        ),
                        _negated=True,
                    ),
                    ("resolved_at__isnull", False),
                    _connector="OR",
                ),
                name="reconcile_resolved_has_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="runtimesession",
            index=models.Index(
                fields=["persona", "started_at"], name="runtime_ses_persona_569fa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runtimesession",
            index=models.Index(
                fields=["status", "started_at"], name="runtime_ses_status_8cf7d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runtimesession",
            index=models.Index(
                fields=["lease_expires_at"], name="runtime_ses_lease_e_93e848_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_write", True), ("status", "OPEN")),
                fields=("persona",),
                name="runtime_session_one_write_per_persona",
            ),
        ),
        migrations.AddConstraint(
            model_name="runtimesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("ended_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="runtime_session_ends_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="workerjob",
            index=models.Index(
                fields=["queue", "status", "run_after"],
                name="runtime_wor_queue_cb9c68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerjob",
            index=models.Index(
                fields=["action"], name="runtime_wor_action__ea875e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workerjob",
            index=models.Index(
                condition=models.Q(("status__in", ["PENDING", "RETRY"])),
                fields=["queue", "run_after"],
                name="worker_job_claimable_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workerjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__lte", models.F("max_attempts"))),
                name="worker_job_attempt_within_max",
            ),
        ),
    ]
