# Generated by Django 5.2.17 on 2026-09-21 08:21

import uuid

import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_f6_suppression"),
        ("runtime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircuitBreaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adapter_key", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CLOSED", "CLOSED"),
                            ("OPEN", "OPEN"),
                            ("HALF_OPEN", "HALF_OPEN"),
                        ],
                        default=common.enums.BreakerState["CLOSED"],
                        max_length=16,
                    ),
                ),
                (
                    "failures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ISO vremena grešaka u prozoru od 60 s.",
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("probes", models.PositiveSmallIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakers",
                        to="channels.channelaccount",
                    ),
                ),
            ],
            options={
                "db_table": "runtime_circuit_breaker",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adapter_key", "account"),
                        name="circuit_breaker_unique_pair",
                    )
                ],
            },
        ),
    ]
