# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        # Canon §10.5 — ekstenzija mora postojati pre kolone tipa vector.
        # Šema v0.1 je to vodila kao zasebnu migraciju 0001_common_extensions;
        # ovde stoji kao prva operacija app-a koji je jedini koristi.
        VectorExtension(),
        migrations.CreateModel(
            name="MemoryContradiction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detected_at", models.DateTimeField()),
                ("detector", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default=common.enums.RiskClass["LOW"],
                        max_length=16,
                    ),
                ),
                ("status", models.CharField(default="OPEN", max_length=24)),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "memory_contradiction",
            },
        ),
        migrations.CreateModel(
            name="MemoryEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_key", models.CharField(max_length=120)),
                (
                    "dimensions",
                    models.PositiveSmallIntegerField(
                        help_text="Zapisano uz vektor: Canon §10.5 traži novu kolonu, ne izmenu."
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
            ],
            options={
                "db_table": "memory_embedding",
            },
        ),
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("working", "working"),
                            ("episodic", "episodic"),
                            ("semantic", "semantic"),
                            ("procedural", "procedural"),
                            ("social", "social"),
                            ("content", "content"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PINNED", "PINNED"),
                            ("ACTIVE", "ACTIVE"),
                            ("ARCHIVED", "ARCHIVED"),
                            ("SUPERSEDED", "SUPERSEDED"),
                            ("DELETED", "DELETED"),
                        ],
                        default=common.enums.MemoryStatus["ACTIVE"],
                        max_length=24,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "PRIVATE"),
                            ("PERSONA_SHARED", "PERSONA_SHARED"),
                            ("TEAM_SHARED", "TEAM_SHARED"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        default=common.enums.MemoryVisibility["PRIVATE"],
                        max_length=24,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("user_provided", "user_provided"),
                            ("generated", "generated"),
                            ("inferred", "inferred"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=220)),
                ("content", models.TextField()),
                (
                    "salience",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "goal_relevance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "novelty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "sensitivity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Ulazi kao sensitivity_penalty u eligibility (§10.2).",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_recalled_at", models.DateTimeField(blank=True, null=True)),
                ("recall_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "memory_item",
            },
        ),
        migrations.CreateModel(
            name="MemoryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("related", "related"),
                            ("supports", "supports"),
                            ("contradicts", "contradicts"),
                            ("derived", "derived"),
                            ("supersedes", "supersedes"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "memory_link",
            },
        ),
        migrations.CreateModel(
            name="MemorySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("system_observation", "system_observation"),
                            ("first_party_user_input", "first_party_user_input"),
                            ("public_web_source", "public_web_source"),
                            ("llm_inference", "llm_inference"),
                            ("synthetic_world_event", "synthetic_world_event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=500)),
                ("observed_at", models.DateTimeField()),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Polazna vrednost iz SOURCE_CONFIDENCE (Canon §10.4).",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "memory_source",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("system_observation", "system_observation"),
                            ("first_party_user_input", "first_party_user_input"),
                            ("public_web_source", "public_web_source"),
                            ("llm_inference", "llm_inference"),
                            ("synthetic_world_event", "synthetic_world_event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("uri", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "trust_score",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "robots_allowed",
                    models.BooleanField(
                        blank=True,
                        help_text="Canon §12.6 — web.read_public traži robots_respected.",
                        null=True,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL znači izvor deljen između persona.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sources",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "memory_knowledge_source",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=220)),
                ("predicate", models.CharField(max_length=120)),
                ("object_json", models.JSONField(blank=True, default=dict)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("user_provided", "user_provided"),
                            ("generated", "generated"),
                            ("inferred", "inferred"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_facts",
                        to="personas.persona",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="memory.knowledgesource",
                    ),
                ),
            ],
            options={
                "db_table": "memory_knowledge_fact",
            },
        ),
        migrations.CreateModel(
            name="MemoryContextPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("planning", "planning"),
                            ("content_draft", "content_draft"),
                            ("reply", "reply"),
                            ("summarise", "summarise"),
                            ("classify", "classify"),
                            ("embed", "embed"),
                            ("evaluate", "evaluate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("query_text", models.TextField(blank=True)),
                (
                    "memory_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UUID-jevi odabranih memorija, redom.",
                    ),
                ),
                (
                    "scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"<memory_id>": {"R": 0.81, "semantic": 0.74}}',
                    ),
                ),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("truncated", models.BooleanField(default=False)),
                ("pack_hash", models.CharField(max_length=64)),
                ("built_at", models.DateTimeField()),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_packs",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "memory_context_pack",
            },
        ),
    ]
