# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memory", "0001_initial"),
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorycontextpack",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context_packs",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="memorycontradiction",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contradictions",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memoryembedding",
            name="memory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorycontradiction",
            name="left",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contradictions_as_left",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorycontradiction",
            name="resolved_memory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_contradictions",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorycontradiction",
            name="right",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contradictions_as_right",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorylink",
            name="from_memory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_out",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorylink",
            name="to_memory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_in",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorysource",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memory_sources",
                to="orchestration.action",
            ),
        ),
        migrations.AddField(
            model_name="memorysource",
            name="knowledge_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_memories",
                to="memory.knowledgesource",
            ),
        ),
        migrations.AddField(
            model_name="memorysource",
            name="memory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="memory.memoryitem",
            ),
        ),
        migrations.AddField(
            model_name="memorysource",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memory_sources",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["persona", "is_active"], name="memory_know_persona_2377c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["checksum"], name="memory_know_checksu_ef6131_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgesource",
            constraint=models.CheckConstraint(
                condition=models.Q(("trust_score__gte", 0), ("trust_score__lte", 1)),
                name="knowledge_source_trust_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgefact",
            index=models.Index(
                fields=["persona", "subject", "predicate"],
                name="memory_know_persona_17b937_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgefact",
            index=models.Index(
                fields=["source"], name="memory_know_source__beee55_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgefact",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="knowledge_fact_confidence_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="memorycontextpack",
            index=models.Index(
                fields=["run", "built_at"], name="memory_cont_run_id_c8a12d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memorycontextpack",
            index=models.Index(
                fields=["persona", "purpose", "built_at"],
                name="memory_cont_persona_b42332_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["persona", "memory_type", "created_at"],
                name="memory_item_persona_25287c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["persona", "status", "expires_at"],
                name="memory_item_persona_192fc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["persona", "salience"], name="memory_item_persona_45755f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("salience__gte", 0), ("salience__lte", 1)),
                name="memory_salience_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="memory_confidence_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("goal_relevance__gte", 0), ("goal_relevance__lte", 1)
                ),
                name="memory_goal_relevance_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("novelty__gte", 0), ("novelty__lte", 1)),
                name="memory_novelty_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("sensitivity__gte", 0), ("sensitivity__lte", 1)),
                name="memory_sensitivity_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "SUPERSEDED"), _negated=True),
                    ("superseded_by__isnull", False),
                    _connector="OR",
                ),
                name="memory_superseded_has_successor",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryembedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="memory_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryembedding",
            constraint=models.UniqueConstraint(
                fields=("memory", "model_key"), name="memory_embedding_unique_model"
            ),
        ),
        migrations.AddIndex(
            model_name="memorycontradiction",
            index=models.Index(
                fields=["persona", "status", "detected_at"],
                name="memory_cont_persona_ff4025_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="memorycontradiction",
            constraint=models.UniqueConstraint(
                fields=("left", "right"), name="memory_contradiction_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="memorycontradiction",
            constraint=models.CheckConstraint(
                condition=models.Q(("left", models.F("right")), _negated=True),
                name="memory_contradiction_no_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="memorylink",
            constraint=models.UniqueConstraint(
                fields=("from_memory", "to_memory", "relation"),
                name="memory_link_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="memorylink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_memory", models.F("to_memory")), _negated=True
                ),
                name="memory_link_no_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="memorylink",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0), ("weight__lte", 1)),
                name="memory_link_weight_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="memorysource",
            index=models.Index(
                fields=["memory", "observed_at"], name="memory_sour_memory__f4d364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memorysource",
            index=models.Index(
                fields=["source_kind", "observed_at"],
                name="memory_sour_source__d9bbdd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="memorysource",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="memory_source_confidence_unit",
            ),
        ),
    ]
