# Generated by Django 5.2.17 on 2026-09-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0002_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryembedding",
            name="text_hash",
            field=models.CharField(
                blank=True,
                help_text="Memory v0.1 §6 — isti tekst i isti model → vektor se ne računa ponovo.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="assertion_predicate",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="assertion_subject",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="assertion_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="source_event_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Teme; po njima konsolidacija grupiše epizode.",
            ),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                condition=models.Q(("assertion_predicate", ""), _negated=True),
                fields=["persona", "assertion_subject", "assertion_predicate"],
                name="memory_assertion_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["persona", "content_hash"], name="memory_content_hash_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_event_id__isnull", False)),
                fields=("persona", "source_event_id", "memory_type"),
                name="memory_unique_source_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assertion_predicate", ""),
                    models.Q(("assertion_subject", ""), _negated=True),
                    _connector="OR",
                ),
                name="memory_assertion_has_subject",
            ),
        ),
    ]
