# Generated by Django 5.2.17 on 2026-09-24 09:18

import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0003_f4_memory_engine"),
        ("personas", "0002_f11_org_and_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryitem",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Popunjeno samo kad je `scope=department`.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="personas.department",
            ),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = izvorni zapis; 1+ = sažetak nastao pečaćenjem.",
            ),
        ),
        migrations.AddField(
            model_name="memoryitem",
            name="scope",
            field=models.CharField(
                choices=[
                    ("persona", "persona"),
                    ("department", "department"),
                    ("company", "company"),
                ],
                default=common.enums.MemoryScope["PERSONA"],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="memoryitem",
            name="persona",
            field=models.ForeignKey(
                help_text="Čiji je rad proizveo zapis. Kod zajedničke memorije ostaje autor, a ko sme da čita određuje `scope` (ADR-0020).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="personas.persona",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["scope", "department", "status"],
                name="memory_item_scope_c78386_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memoryitem",
            index=models.Index(
                fields=["persona", "scope", "level", "status"],
                name="memory_item_persona_8fcb87_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("department__isnull", False), ("scope", "department")),
                    models.Q(
                        models.Q(("scope", "department"), _negated=True),
                        ("department__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="memory_department_matches_scope",
            ),
        ),
    ]
