# Generated by Django 5.2.17 on 2026-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "INFO"),
                            ("NOTICE", "NOTICE"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_key", models.CharField(max_length=120)),
                (
                    "actor_ref",
                    models.CharField(
                        blank=True,
                        help_text="Čovek ili servis koji je izazvao događaj.",
                        max_length=180,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("viewer", "viewer"),
                            ("operator", "operator"),
                            ("persona_manager", "persona_manager"),
                            ("trust_safety", "trust_safety"),
                            ("runtime_admin", "runtime_admin"),
                            ("system_admin", "system_admin"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sanitizovano — bez tajni (Canon §17).",
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "observability_audit_event",
            },
        ),
        migrations.CreateModel(
            name="CostLedger",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cost_bucket",
                    models.CharField(
                        choices=[
                            ("llm", "llm"),
                            ("embeddings", "embeddings"),
                            ("media_generation", "media_generation"),
                            ("browser_minutes", "browser_minutes"),
                            ("storage", "storage"),
                            ("egress", "egress"),
                            ("x_api_credits", "x_api_credits"),
                            ("third_party_api", "third_party_api"),
                        ],
                        max_length=24,
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit", models.CharField(max_length=32)),
                (
                    "amount_eur_cents",
                    models.BigIntegerField(help_text="Kanonska valuta (Canon §13.1)."),
                ),
                ("source_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "source_amount_minor",
                    models.BigIntegerField(
                        help_text="Iznos u najmanjoj jedinici izvorne valute."
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Dnevni ECB referentni kurs, keširan.",
                        max_digits=12,
                    ),
                ),
                (
                    "fx_date",
                    models.DateField(help_text="Dan NASTANKA troška, ne dan obračuna."),
                ),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("provider_ref", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "db_table": "observability_cost_ledger",
            },
        ),
        migrations.CreateModel(
            name="MetricPoint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("metric", models.CharField(max_length=120)),
                (
                    "channel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEBSITE", "WEBSITE"),
                            ("NEWSLETTER", "NEWSLETTER"),
                            ("EMAIL", "EMAIL"),
                            ("LINKEDIN", "LINKEDIN"),
                            ("INSTAGRAM", "INSTAGRAM"),
                            ("FACEBOOK", "FACEBOOK"),
                            ("X", "X"),
                            ("TIKTOK", "TIKTOK"),
                            ("YOUTUBE", "YOUTUBE"),
                            ("SANDBOX", "SANDBOX"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("unit", models.CharField(blank=True, max_length=24)),
                ("recorded_at", models.DateTimeField()),
                (
                    "dimensions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ograničena kardinalnost — vidi docstring.",
                    ),
                ),
            ],
            options={
                "db_table": "observability_metric_point",
            },
        ),
    ]
