# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("observability", "0001_initial"),
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="orchestration.action",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="costledger",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_entries",
                to="orchestration.action",
            ),
        ),
        migrations.AddField(
            model_name="costledger",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_entries",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="costledger",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_entries",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="metricpoint",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="metric_points",
                to="personas.persona",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["occurred_at"], name="observabili_occurre_b136ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_key", "occurred_at"],
                name="observabili_event_k_052dfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["persona", "occurred_at"], name="observabili_persona_9eceed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["trace_id"], name="observabili_trace_i_edb07d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costledger",
            index=models.Index(
                fields=["persona", "occurred_at"], name="observabili_persona_6a1837_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costledger",
            index=models.Index(
                fields=["cost_bucket", "occurred_at"],
                name="observabili_cost_bu_1b7a39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costledger",
            index=models.Index(
                fields=["provider", "occurred_at"],
                name="observabili_provide_2bb49f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costledger",
            index=models.Index(fields=["run"], name="observabili_run_id_fed5de_idx"),
        ),
        migrations.AddConstraint(
            model_name="costledger",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_eur_cents__gte", 0)),
                name="cost_ledger_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="costledger",
            constraint=models.CheckConstraint(
                condition=models.Q(("fx_rate__gt", 0)),
                name="cost_ledger_fx_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="costledger",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_currency", "EUR"), _negated=True),
                    ("fx_rate", 1),
                    _connector="OR",
                ),
                name="cost_ledger_eur_rate_is_one",
            ),
        ),
        migrations.AddIndex(
            model_name="metricpoint",
            index=models.Index(
                fields=["metric", "recorded_at"], name="observabili_metric_307ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metricpoint",
            index=models.Index(
                fields=["persona", "recorded_at"], name="observabili_persona_02a0bb_idx"
            ),
        ),
    ]
