# Generated by Django 5.2.17 on 2026-09-21 05:20

from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("observability", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("consumer", models.CharField(max_length=80)),
                ("event_id", models.CharField(max_length=32)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "observability_event_delivery",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "event_id"), name="event_delivery_once"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventOutbox",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.CharField(max_length=32, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                ("event_version", models.PositiveSmallIntegerField(default=1)),
                ("persona_public_id", models.CharField(blank=True, max_length=16)),
                (
                    "envelope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ceo Canon §7.1 envelope, već validiran šemom.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("DEAD", "DEAD"),
                        ],
                        default=common.enums.OutboxStatus["PENDING"],
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "observability_event_outbox",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "PENDING")),
                        fields=["id"],
                        name="event_outbox_pending_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="observabili_event_t_2439e2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(help_text="Ko je poslao zahtev.", max_length=160),
                ),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=500)),
                ("status_code", models.PositiveSmallIntegerField(default=0)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "observability_idempotency_record",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="observabili_expires_add9c6_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key"), name="idempotency_unique_key"
                    )
                ],
            },
        ),
    ]
