# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("purpose", models.CharField(blank=True, max_length=120)),
                ("is_public_pool", models.BooleanField(default=False)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_collections",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "visuals_asset_collection",
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("AVATAR", "AVATAR"),
                            ("FACE_REFERENCE", "FACE_REFERENCE"),
                            ("PHOTO", "PHOTO"),
                            ("VIDEO", "VIDEO"),
                            ("AUDIO", "AUDIO"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("THUMBNAIL", "THUMBNAIL"),
                        ],
                        max_length=24,
                    ),
                ),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                ("mime_type", models.CharField(max_length=100)),
                ("sha256", models.CharField(max_length=64)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("origin", models.CharField(max_length=32)),
                ("generation_model", models.CharField(blank=True, max_length=120)),
                ("generation_prompt_hash", models.CharField(blank=True, max_length=64)),
                ("rights_note", models.TextField(blank=True)),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "visuals_media_asset",
            },
        ),
        migrations.CreateModel(
            name="AssetCollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField()),
                ("labels", models.JSONField(blank=True, default=list)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="visuals.assetcollection",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="visuals.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "visuals_asset_collection_item",
            },
        ),
        migrations.CreateModel(
            name="VisualProfile",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="visual_profile",
                        serialize=False,
                        to="personas.persona",
                    ),
                ),
                ("style_prompt", models.TextField()),
                ("negative_prompt", models.TextField(blank=True)),
                ("age_appearance", models.CharField(blank=True, max_length=80)),
                ("hair", models.CharField(blank=True, max_length=120)),
                ("eyes", models.CharField(blank=True, max_length=80)),
                ("wardrobe_style", models.CharField(blank=True, max_length=160)),
                ("brand_palette", models.JSONField(blank=True, default=dict)),
                ("consistency_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reference_for",
                        to="visuals.mediaasset",
                    ),
                ),
            ],
            options={
                "db_table": "visuals_visual_profile",
            },
        ),
        migrations.AddConstraint(
            model_name="assetcollection",
            constraint=models.UniqueConstraint(
                fields=("persona", "name"), name="asset_collection_unique_name"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["persona", "kind", "created_at"],
                name="visuals_med_persona_e05571_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["sha256"], name="visuals_med_sha256_f14d6b_idx"),
        ),
        migrations.AddConstraint(
            model_name="assetcollectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "asset"), name="collection_item_unique_asset"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetcollectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "position"),
                name="collection_item_unique_position",
            ),
        ),
    ]
