# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_bucket",
                    models.CharField(
                        choices=[
                            ("llm", "llm"),
                            ("embeddings", "embeddings"),
                            ("media_generation", "media_generation"),
                            ("browser_minutes", "browser_minutes"),
                            ("storage", "storage"),
                            ("egress", "egress"),
                            ("x_api_credits", "x_api_credits"),
                            ("third_party_api", "third_party_api"),
                        ],
                        default=common.enums.CostBucket["LLM"],
                        max_length=24,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cached_input_tokens", models.PositiveIntegerField(default=0)),
                ("reasoning_tokens", models.PositiveIntegerField(default=0)),
                ("amount_eur_cents", models.BigIntegerField(default=0)),
                (
                    "is_estimated",
                    models.BooleanField(
                        default=True,
                        help_text="False kada je potvrđeno iz provajderovog izveštaja.",
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
            ],
            options={
                "db_table": "llm_gateway_usage",
            },
        ),
        migrations.CreateModel(
            name="PromptRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("planning", "planning"),
                            ("content_draft", "content_draft"),
                            ("reply", "reply"),
                            ("summarise", "summarise"),
                            ("classify", "classify"),
                            ("embed", "embed"),
                            ("evaluate", "evaluate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("system_hash", models.CharField(blank=True, max_length=64)),
                ("prompt_hash", models.CharField(max_length=64)),
                ("response_hash", models.CharField(blank=True, max_length=64)),
                ("prompt_ref", models.CharField(blank=True, max_length=512)),
                ("response_ref", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("finish_reason", models.CharField(blank=True, max_length=40)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "llm_gateway_prompt_record",
            },
        ),
        migrations.CreateModel(
            name="LLMRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("planning", "planning"),
                            ("content_draft", "content_draft"),
                            ("reply", "reply"),
                            ("summarise", "summarise"),
                            ("classify", "classify"),
                            ("embed", "embed"),
                            ("evaluate", "evaluate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("provider", models.CharField(max_length=80)),
                ("model_key", models.CharField(max_length=160)),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Manji broj = prvi izbor; sledeći je fallback.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("context_window", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.7,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=60)),
                ("input_price_micro_eur_per_1k", models.BigIntegerField(default=0)),
                ("output_price_micro_eur_per_1k", models.BigIntegerField(default=0)),
                (
                    "data_training_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="True samo ako provajder izričito NE trenira na našim podacima.",
                    ),
                ),
                ("is_openai_compatible", models.BooleanField(default=True)),
                (
                    "quota_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RPM, TPM, dnevni limit, datum isteka besplatne kvote.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "llm_gateway_route",
                "indexes": [
                    models.Index(
                        fields=["purpose", "is_enabled", "priority"],
                        name="llm_gateway_purpose_969b86_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purpose", "provider", "model_key"),
                        name="llm_route_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("temperature__gte", 0), ("temperature__lte", 1)
                        ),
                        name="llm_route_temperature_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("input_price_micro_eur_per_1k__gte", 0),
                            ("output_price_micro_eur_per_1k__gte", 0),
                        ),
                        name="llm_route_prices_non_negative",
                    ),
                ],
            },
        ),
    ]
