# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("llm_gateway", "0001_initial"),
        ("memory", "0001_initial"),
        ("observability", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="cost_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_usage",
                to="observability.costledger",
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usage",
                to="llm_gateway.llmroute",
            ),
        ),
        migrations.AddField(
            model_name="promptrecord",
            name="context_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_records",
                to="memory.memorycontextpack",
            ),
        ),
        migrations.AddField(
            model_name="promptrecord",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_records",
                to="personas.persona",
            ),
        ),
    ]
