# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("llm_gateway", "0002_initial"),
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptrecord",
            name="plan_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_records",
                to="orchestration.planstep",
            ),
        ),
        migrations.AddField(
            model_name="promptrecord",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prompt_records",
                to="llm_gateway.llmroute",
            ),
        ),
        migrations.AddField(
            model_name="promptrecord",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_records",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="prompt_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage",
                to="llm_gateway.promptrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="promptrecord",
            index=models.Index(
                fields=["run", "started_at"], name="llm_gateway_run_id_b6ac04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptrecord",
            index=models.Index(
                fields=["persona", "purpose", "started_at"],
                name="llm_gateway_persona_31a378_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptrecord",
            index=models.Index(
                fields=["prompt_hash"], name="llm_gateway_prompt__5b554c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(
                fields=["route", "recorded_at"], name="llm_gateway_route_i_261dd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(
                fields=["recorded_at"], name="llm_gateway_recorde_2fce15_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_eur_cents__gte", 0)),
                name="llm_usage_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmusage",
            constraint=models.UniqueConstraint(
                fields=("prompt_record", "cost_bucket"),
                name="llm_usage_unique_bucket_per_call",
            ),
        ),
    ]
