# Generated by Django 5.2.17 on 2026-09-24 13:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_gateway", "0003_initial"),
        ("personas", "0002_f11_org_and_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmroute",
            name="base_url",
            field=models.CharField(
                blank=True,
                help_text="Adresa API-ja provajdera. Nije tajna, pa sme u bazu; prazno znači „uzmi iz podešavanja” (ADR-0026).",
                max_length=300,
            ),
        ),
        migrations.CreateModel(
            name="AgentCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                ("credential_ref", models.CharField(max_length=512)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("fingerprint", models.CharField(blank=True, max_length=8)),
                ("set_by", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_credentials",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "llm_gateway_agent_credential",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "provider"), name="agent_credential_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("credential_ref__regex", "^(env|file):.")),
                        name="agent_credential_is_reference_only",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("planning", "planning"),
                            ("content_draft", "content_draft"),
                            ("reply", "reply"),
                            ("summarise", "summarise"),
                            ("classify", "classify"),
                            ("embed", "embed"),
                            ("evaluate", "evaluate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_routes",
                        to="personas.persona",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_routes",
                        to="llm_gateway.llmroute",
                    ),
                ),
            ],
            options={
                "db_table": "llm_gateway_agent_route",
                "indexes": [
                    models.Index(
                        fields=["persona", "purpose", "is_enabled", "priority"],
                        name="llm_gateway_persona_5ea9b1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "purpose", "route"),
                        name="agent_route_unique",
                    )
                ],
            },
        ),
    ]
