# Generated by Django 5.2.17 on 2026-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_gateway", "0004_llmroute_base_url_agentcredential_agentroute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentroute",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("planning", "planning"),
                    ("content_draft", "content_draft"),
                    ("reply", "reply"),
                    ("summarise", "summarise"),
                    ("classify", "classify"),
                    ("embed", "embed"),
                    ("evaluate", "evaluate"),
                    ("code_patch", "code_patch"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="llmroute",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("planning", "planning"),
                    ("content_draft", "content_draft"),
                    ("reply", "reply"),
                    ("summarise", "summarise"),
                    ("classify", "classify"),
                    ("embed", "embed"),
                    ("evaluate", "evaluate"),
                    ("code_patch", "code_patch"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="promptrecord",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("planning", "planning"),
                    ("content_draft", "content_draft"),
                    ("reply", "reply"),
                    ("summarise", "summarise"),
                    ("classify", "classify"),
                    ("embed", "embed"),
                    ("evaluate", "evaluate"),
                    ("code_patch", "code_patch"),
                ],
                max_length=24,
            ),
        ),
    ]
