# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("RETRYABLE_ERROR", "RETRYABLE_ERROR"),
                            ("PERMANENT_ERROR", "PERMANENT_ERROR"),
                            ("DENIED_BY_POLICY", "DENIED_BY_POLICY"),
                            ("BLOCKED_BY_PLATFORM", "BLOCKED_BY_PLATFORM"),
                            ("CAPABILITY_UNAVAILABLE", "CAPABILITY_UNAVAILABLE"),
                            (
                                "PLATFORM_POLICY_REQUIRES_HUMAN",
                                "PLATFORM_POLICY_REQUIRES_HUMAN",
                            ),
                            ("DISCLOSURE_MISSING", "DISCLOSURE_MISSING"),
                            ("NEEDS_AUTH", "NEEDS_AUTH"),
                            ("NEEDS_HUMAN", "NEEDS_HUMAN"),
                            ("ABORTED_SAFE", "ABORTED_SAFE"),
                            ("UNKNOWN_EFFECT", "UNKNOWN_EFFECT"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        help_text="Canon §3.9 — `OUTCOME_REASON_CODE`.",
                        max_length=48,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "NONE"),
                            ("RESPONSE_ONLY", "RESPONSE_ONLY"),
                            ("SCREENSHOT", "SCREENSHOT"),
                            ("SCREENSHOT_AND_DOM", "SCREENSHOT_AND_DOM"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "evidence_ref",
                    models.CharField(
                        blank=True,
                        help_text="Ključ u object storage-u.",
                        max_length=512,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                ("error_detail", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "orchestration_action_attempt",
            },
        ),
        migrations.CreateModel(
            name="AgentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                ("goal", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("ACTIVE", "ACTIVE"),
                            ("COMPLETED", "COMPLETED"),
                            ("SUPERSEDED", "SUPERSEDED"),
                            ("ABANDONED", "ABANDONED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default=common.enums.PlanStatus["DRAFT"],
                        max_length=24,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "orchestration_agent_plan",
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                (
                    "wake_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPERATOR_TASK", "OPERATOR_TASK"),
                            ("APPROVAL_DECISION", "APPROVAL_DECISION"),
                            ("INBOUND_HIGH", "INBOUND_HIGH"),
                            ("GOAL_DEADLINE", "GOAL_DEADLINE"),
                            ("WORLD_EVENT_HIGH", "WORLD_EVENT_HIGH"),
                            ("ROUTINE_WINDOW", "ROUTINE_WINDOW"),
                            ("MAINTENANCE", "MAINTENANCE"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("ABORTED", "ABORTED"),
                            ("FAILED", "FAILED"),
                        ],
                        default=common.enums.RunStatus["RUNNING"],
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("prompt_hash", models.CharField(blank=True, max_length=64)),
                ("decisions_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "cost_eur_cents",
                    models.BigIntegerField(
                        default=0,
                        help_text="Canon §13.1 — EUR u centima, nikada float.",
                    ),
                ),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "orchestration_agent_run",
            },
        ),
        migrations.CreateModel(
            name="PlanStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.SmallIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("think", "think"),
                            ("retrieve", "retrieve"),
                            ("create", "create"),
                            ("action", "action"),
                            ("wait", "wait"),
                            ("review", "review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("READY", "READY"),
                            ("RUNNING", "RUNNING"),
                            ("DONE", "DONE"),
                            ("SKIPPED", "SKIPPED"),
                            ("FAILED", "FAILED"),
                        ],
                        default=common.enums.StepStatus["PENDING"],
                        max_length=24,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("input_json", models.JSONField(blank=True, default=dict)),
                ("output_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "orchestration_plan_step",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                (
                    "action_type",
                    models.CharField(
                        help_text="Canon §6.4: `channel.post.create`, `mail.send`…",
                        max_length=64,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        blank=True,
                        help_text="Canon §6.4 — ključ iz `policy/capabilities.yaml`.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "PROPOSED"),
                            ("POLICY_CHECK", "POLICY_CHECK"),
                            ("APPROVAL_PENDING", "APPROVAL_PENDING"),
                            ("QUEUED", "QUEUED"),
                            ("RUNNING", "RUNNING"),
                            ("RETRY_WAIT", "RETRY_WAIT"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                            ("BLOCKED", "BLOCKED"),
                            ("CANCELLED", "CANCELLED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default=common.enums.ActionStatus["PROPOSED"],
                        max_length=24,
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_class",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default=common.enums.RiskClass["LOW"],
                        max_length=16,
                    ),
                ),
                ("target_ref", models.CharField(blank=True, max_length=500)),
                ("intent", models.TextField()),
                ("input_json", models.JSONField(blank=True, default=dict)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Canon §15.3 — mora odgovarati ApprovalRequest.payload_hash.",
                        max_length=64,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Canon §6.3 — sha256(persona|type|target|content|step), TTL ≥ 24 h.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "deadline_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Canon §12.6 — rok IZVRŠENJA; rok odobrenja je drugo polje.",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "channel_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="channels.channelaccount",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_action",
            },
        ),
    ]
