# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("behaviour", "0002_initial"),
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
        ("policy", "0001_initial"),
        ("runtime", "0001_initial"),
        ("social_graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="policy_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Canon §6.2 — obavezno od QUEUED nadalje.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="policy.policydecision",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="target_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_actions",
                to="social_graph.actor",
            ),
        ),
        migrations.AddField(
            model_name="actionattempt",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="orchestration.action",
            ),
        ),
        migrations.AddField(
            model_name="actionattempt",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="runtime.runtimesession",
            ),
        ),
        migrations.AddField(
            model_name="agentplan",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="agentplan",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="orchestration.agentplan",
            ),
        ),
        migrations.AddField(
            model_name="agentplan",
            name="trigger_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="behaviour.worldevent",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="trigger_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="behaviour.worldevent",
            ),
        ),
        migrations.AddField(
            model_name="agentplan",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="planstep",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="orchestration.planstep",
            ),
        ),
        migrations.AddField(
            model_name="planstep",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="orchestration.agentplan",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="plan_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="orchestration.planstep",
            ),
        ),
        migrations.AddIndex(
            model_name="actionattempt",
            index=models.Index(
                fields=["action", "attempt_number"],
                name="orchestrati_action__bf0288_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actionattempt",
            index=models.Index(
                fields=["outcome", "started_at"], name="orchestrati_outcome_e75fde_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="actionattempt",
            constraint=models.UniqueConstraint(
                fields=("action", "attempt_number"), name="action_attempt_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="actionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_number__gte", 1)),
                name="action_attempt_number_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["persona", "started_at"], name="orchestrati_persona_593a24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "started_at"], name="orchestrati_status_c98e88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["trace_id"], name="orchestrati_trace_i_79361f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("ended_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="agent_run_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_eur_cents__gte", 0)),
                name="agent_run_cost_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="agentplan",
            index=models.Index(
                fields=["persona", "status", "priority"],
                name="orchestrati_persona_c8a344_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentplan",
            index=models.Index(
                fields=["valid_until"], name="orchestrati_valid_u_cd150c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentplan",
            index=models.Index(fields=["run"], name="orchestrati_run_id_db3229_idx"),
        ),
        migrations.AddIndex(
            model_name="planstep",
            index=models.Index(
                fields=["plan", "status"], name="orchestrati_plan_id_10183d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planstep",
            constraint=models.UniqueConstraint(
                fields=("plan", "sequence"), name="plan_step_unique_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="planstep",
            constraint=models.CheckConstraint(
                condition=models.Q(("depends_on", models.F("id")), _negated=True),
                name="plan_step_no_self_dependency",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["status", "scheduled_for"], name="orchestrati_status_7da40c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["persona", "created_at"], name="orchestrati_persona_6ced5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["action_type", "risk_class", "status"],
                name="orchestrati_action__ce4f59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["trace_id"], name="orchestrati_trace_i_7f7430_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(("risk_score__gte", 0), ("risk_score__lte", 100)),
                name="action_risk_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            ("QUEUED", "RUNNING", "RETRY_WAIT", "SUCCEEDED"),
                        ),
                        _negated=True,
                    ),
                    ("policy_decision__isnull", False),
                    _connector="OR",
                ),
                name="action_requires_policy_decision",
            ),
        ),
    ]
