# Generated by Django 5.2.17 on 2026-09-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behaviour", "0002_initial"),
        ("orchestration", "0002_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[("ACT", "ACT"), ("SKIP", "SKIP"), ("DEFER", "DEFER")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROUTINE_WINDOW_DUE", "ROUTINE_WINDOW_DUE"),
                    ("OPERATOR_TASK", "OPERATOR_TASK"),
                    ("WORLD_EVENT_RELEVANT", "WORLD_EVENT_RELEVANT"),
                    ("EVENT_DEFERRED", "EVENT_DEFERRED"),
                    ("NO_WINDOW", "NO_WINDOW"),
                    ("REST_WINDOW", "REST_WINDOW"),
                    ("ROUTINE_NOT_SELECTED", "ROUTINE_NOT_SELECTED"),
                    ("WINDOW_LIMIT_REACHED", "WINDOW_LIMIT_REACHED"),
                    ("LOW_ENERGY_OR_BUDGET", "LOW_ENERGY_OR_BUDGET"),
                    ("OVERLOADED", "OVERLOADED"),
                    ("COOLDOWN_ACTIVE", "COOLDOWN_ACTIVE"),
                    ("PERSONA_PAUSED", "PERSONA_PAUSED"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="wake_key",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["persona", "decision", "started_at"],
                name="orchestrati_persona_932008_idx",
            ),
        ),
    ]
