# Generated by Django 5.2.17 on 2026-09-24 23:30

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.orchestration.models
import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0003_f3_run_decision"),
        ("personas", "0002_f11_org_and_dossier"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "why",
                    models.TextField(
                        help_text="Poslovni razlog, ne rešenje (ADR-0034 §4)."
                    ),
                ),
                ("adr", models.CharField(blank=True, max_length=80)),
                ("allowed_paths", models.JSONField(blank=True, default=list)),
                (
                    "required_gates",
                    models.JSONField(
                        blank=True, default=apps.orchestration.models.default_gates
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("READY", "READY"),
                            ("ASSIGNED", "ASSIGNED"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("IN_REVIEW", "IN_REVIEW"),
                            ("BLOCKED", "BLOCKED"),
                            ("DONE", "DONE"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default=common.enums.TaskStatus["DRAFT"],
                        max_length=24,
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, max_length=40)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_assigned",
                        to="personas.persona",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="orchestration.agentplan",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_requested",
                        to="personas.persona",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_reviewing",
                        to="personas.persona",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="orchestration.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_code_task",
            },
        ),
        migrations.CreateModel(
            name="GateResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gate",
                    models.CharField(
                        choices=[
                            ("pytest", "pytest"),
                            ("ruff", "ruff"),
                            ("canon_lint", "canon_lint"),
                            ("migrations", "migrations"),
                            ("review", "review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("passed", models.BooleanField()),
                ("detail", models.TextField(blank=True)),
                ("commit_sha", models.CharField(blank=True, max_length=40)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="orchestration.codetask",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_gate_result",
            },
        ),
        migrations.CreateModel(
            name="ReviewFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.CharField(max_length=300)),
                ("line", models.PositiveIntegerField(blank=True, null=True)),
                ("claim", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("BLOCKER", "BLOCKER"),
                            ("MAJOR", "MAJOR"),
                            ("MINOR", "MINOR"),
                            ("NIT", "NIT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("FIXED", "FIXED"),
                        ],
                        default=common.enums.FindingStatus["OPEN"],
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(default="agent", max_length=40)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings_written",
                        to="personas.persona",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="orchestration.codetask",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_review_finding",
            },
        ),
        migrations.AddIndex(
            model_name="codetask",
            index=models.Index(
                fields=["status", "created_at"], name="orchestrati_status_9c3c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codetask",
            index=models.Index(
                fields=["assignee", "status"], name="orchestrati_assigne_7bd994_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="codetask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reviewer", models.F("assignee")), _negated=True),
                    ("reviewer__isnull", True),
                    ("assignee__isnull", True),
                    _connector="OR",
                ),
                name="code_task_reviewer_is_not_author",
            ),
        ),
        migrations.AddIndex(
            model_name="gateresult",
            index=models.Index(
                fields=["task", "gate", "-created_at"],
                name="orchestrati_task_id_0d99f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewfinding",
            index=models.Index(
                fields=["task", "status", "severity"],
                name="orchestrati_task_id_ac802c_idx",
            ),
        ),
    ]
