# Generated by Django 5.2.17 on 2026-09-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0004_adr_0035_code_task"),
        ("personas", "0002_f11_org_and_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewfinding",
            name="category",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="reviewfinding",
            name="fingerprint",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddConstraint(
            model_name="reviewfinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fingerprint", ""), _negated=True),
                fields=("task", "fingerprint"),
                name="review_finding_unique_fingerprint",
            ),
        ),
    ]
