# Generated by Django 5.2.17 on 2026-09-25 10:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0005_adr_0036_finding_fingerprint"),
        ("personas", "0003_adr_0037_position_needs"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_sha", models.CharField(blank=True, max_length=40)),
                ("diff", models.TextField()),
                ("paths", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "PROPOSED"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("APPLIED", "APPLIED"),
                        ],
                        default=common.enums.PatchStatus["PROPOSED"],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("applied_sha", models.CharField(blank=True, max_length=40)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patches_written",
                        to="personas.persona",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patches",
                        to="orchestration.codetask",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_task_patch",
                "indexes": [
                    models.Index(
                        fields=["task", "status", "-created_at"],
                        name="orchestrati_task_id_95d171_idx",
                    )
                ],
            },
        ),
    ]
