# Generated by Django 5.2.17 on 2026-09-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0006_adr_0038_task_patch"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateresult",
            name="patch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates",
                to="orchestration.taskpatch",
            ),
        ),
    ]
