# Generated by Django 5.2.17 on 2026-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0007_adr_0040_gate_patch"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpatch",
            name="cost_eur_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
