# Generated by Django 5.2.17 on 2026-09-28 08:26

from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0009_zakrpa_od_modela"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpatch",
            name="fault",
            field=models.CharField(
                choices=[("AGENT", "AGENT"), ("SISTEM", "SISTEM"), ("COVEK", "COVEK")],
                default=common.enums.PatchFault["AGENT"],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="taskpatch",
            name="fault_reason",
            field=models.TextField(blank=True),
        ),
    ]
