# Generated by Django 5.2.17 on 2026-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0010_krivica_odbijanja"),
    ]

    operations = [
        migrations.AddField(
            model_name="codetask",
            name="claimed_by",
            field=models.CharField(
                blank=True,
                help_text="Identitet poslušnika koji drži zakup. Prazno = slobodan.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="codetask",
            name="claimed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Do kada zakup važi. Istekao zakup je slobodan zadatak — poslušnik koji padne ne zaključava posao zauvek.",
                null=True,
            ),
        ),
    ]
