# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=32, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "global"),
                            ("channel", "channel"),
                            ("persona", "persona"),
                            ("action", "action"),
                            ("cohort", "cohort"),
                            ("capability", "capability"),
                            ("account", "account"),
                        ],
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "available_at",
                    models.DateTimeField(
                        help_text="Pre ovog trenutka scheduler događaj ne vidi (Canon §11.1)."
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wake_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPERATOR_TASK", "OPERATOR_TASK"),
                            ("APPROVAL_DECISION", "APPROVAL_DECISION"),
                            ("INBOUND_HIGH", "INBOUND_HIGH"),
                            ("GOAL_DEADLINE", "GOAL_DEADLINE"),
                            ("WORLD_EVENT_HIGH", "WORLD_EVENT_HIGH"),
                            ("ROUTINE_WINDOW", "ROUTINE_WINDOW"),
                            ("MAINTENANCE", "MAINTENANCE"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("user_provided", "user_provided"),
                            ("generated", "generated"),
                            ("inferred", "inferred"),
                        ],
                        default=common.enums.Provenance["OBSERVED"],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(blank=True, max_length=220, null=True)),
                ("trace_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "behaviour_world_event",
            },
        ),
        migrations.CreateModel(
            name="BehaviourState",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="behaviour_state",
                        serialize=False,
                        to="personas.persona",
                    ),
                ),
                (
                    "energy",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "valence",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="−1.000 do 1.000. Prikaz: (valence + 1) / 2 — izvedeno, ne polje.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "arousal",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "cognitive_load",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "social_appetite",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "curiosity_now",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Trenutna radoznalost; trajna osobina je TraitProfile.curiosity.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "focus",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "novelty_need",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "stress",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "content_pressure",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "inbox_pressure",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "topic_saturation",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "risk_alert",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "free_minutes",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ]
                    ),
                ),
                (
                    "attention_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Jedinice pažnje, ne minuti.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                ("next_wake_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wake_priority",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Brojčana vrednost iz WAKE_PRIORITY_VALUE (Canon §11.2).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("state_version", models.PositiveIntegerField(default=1)),
                ("last_state_event_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state_ext",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canon §5 — *_ext obrazac, uz JSON Schema.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "behaviour_state",
                "indexes": [
                    models.Index(
                        fields=["next_wake_at", "wake_priority"],
                        name="behaviour_s_next_wa_f33219_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("energy__gte", 0), ("energy__lte", 1)),
                        name="state_energy_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("arousal__gte", 0), ("arousal__lte", 1)),
                        name="state_arousal_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cognitive_load__gte", 0), ("cognitive_load__lte", 1)
                        ),
                        name="state_cognitive_load_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("social_appetite__gte", 0), ("social_appetite__lte", 1)
                        ),
                        name="state_social_appetite_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("curiosity_now__gte", 0), ("curiosity_now__lte", 1)
                        ),
                        name="state_curiosity_now_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("focus__gte", 0), ("focus__lte", 1)),
                        name="state_focus_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("novelty_need__gte", 0), ("novelty_need__lte", 1)
                        ),
                        name="state_novelty_need_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stress__gte", 0), ("stress__lte", 1)),
                        name="state_stress_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("content_pressure__gte", 0), ("content_pressure__lte", 1)
                        ),
                        name="state_content_pressure_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("inbox_pressure__gte", 0), ("inbox_pressure__lte", 1)
                        ),
                        name="state_inbox_pressure_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("topic_saturation__gte", 0), ("topic_saturation__lte", 1)
                        ),
                        name="state_topic_saturation_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("risk_alert__gte", 0), ("risk_alert__lte", 1)
                        ),
                        name="state_risk_alert_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valence__gte", -1), ("valence__lte", 1)),
                        name="state_valence_signed_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("free_minutes__gte", 0), ("free_minutes__lte", 1440)
                        ),
                        name="state_free_minutes_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("attention_remaining__gte", 0),
                            ("attention_remaining__lte", 24),
                        ),
                        name="state_attention_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("wake_priority__gte", 0), ("wake_priority__lte", 100)
                        ),
                        name="state_wake_priority_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutineTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "day_mask",
                    models.SmallIntegerField(
                        help_text="Bit 0 = ponedeljak … bit 6 = nedelja.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(127),
                        ],
                    ),
                ),
                ("active_from", models.DateField(blank=True, null=True)),
                ("active_to", models.DateField(blank=True, null=True)),
                ("priority", models.SmallIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_templates",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_routine_template",
            },
        ),
        migrations.CreateModel(
            name="RoutineWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_type", models.CharField(max_length=64)),
                ("start_local", models.TimeField()),
                ("end_local", models.TimeField()),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("min_minutes", models.SmallIntegerField(blank=True, null=True)),
                ("max_minutes", models.SmallIntegerField(blank=True, null=True)),
                ("constraints_json", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="behaviour.routinetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_routine_window",
            },
        ),
        migrations.CreateModel(
            name="StateDelta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reducer_key", models.CharField(max_length=120)),
                ("from_version", models.PositiveIntegerField()),
                ("to_version", models.PositiveIntegerField()),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"stress": [0.310, 0.480]} — pre i posle.',
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("trace_id", models.UUIDField(blank=True, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_deltas",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_state_delta",
            },
        ),
    ]
