# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("behaviour", "0001_initial"),
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statedelta",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_deltas",
                to="orchestration.agentrun",
            ),
        ),
        migrations.AddField(
            model_name="worldevent",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL za globalne i kohortne događaje.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="world_events",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="statedelta",
            name="world_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_deltas",
                to="behaviour.worldevent",
            ),
        ),
        migrations.AddIndex(
            model_name="routinetemplate",
            index=models.Index(
                fields=["persona", "is_enabled"], name="behaviour_r_persona_f43aef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="routinetemplate",
            constraint=models.UniqueConstraint(
                fields=("persona", "name"), name="routine_template_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="routinetemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_mask__gte", 0), ("day_mask__lte", 127)),
                name="routine_template_day_mask_range",
            ),
        ),
        migrations.AddIndex(
            model_name="routinewindow",
            index=models.Index(
                fields=["template", "start_local"],
                name="behaviour_r_templat_25cdd5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("probability__gte", 0), ("probability__lte", 1)),
                name="routine_window_probability_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_local__lt", models.F("end_local"))),
                name="routine_window_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="routinewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_minutes__isnull", True),
                    ("max_minutes__isnull", True),
                    ("min_minutes__lte", models.F("max_minutes")),
                    _connector="OR",
                ),
                name="routine_window_minutes_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="worldevent",
            index=models.Index(
                fields=["available_at", "priority"],
                name="behaviour_w_availab_a250ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="worldevent",
            index=models.Index(
                fields=["persona", "available_at"],
                name="behaviour_w_persona_e3454f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="worldevent",
            index=models.Index(
                fields=["event_type", "occurred_at"],
                name="behaviour_w_event_t_36aff5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="worldevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key__isnull", False)),
                fields=("dedupe_key",),
                name="world_event_unique_dedupe_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="worldevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("persona__isnull", False), ("scope", "persona")),
                    models.Q(("scope", "persona"), _negated=True),
                    _connector="OR",
                ),
                name="world_event_persona_scope_has_persona",
            ),
        ),
        migrations.AddIndex(
            model_name="statedelta",
            index=models.Index(
                fields=["persona", "occurred_at"], name="behaviour_s_persona_fe0ac8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statedelta",
            index=models.Index(
                fields=["reducer_key", "occurred_at"],
                name="behaviour_s_reducer_c5ff01_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="statedelta",
            constraint=models.UniqueConstraint(
                fields=("persona", "to_version"), name="state_delta_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="statedelta",
            constraint=models.CheckConstraint(
                condition=models.Q(("to_version__gt", models.F("from_version"))),
                name="state_delta_version_advances",
            ),
        ),
    ]
