# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChannelAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "WEBSITE"),
                            ("NEWSLETTER", "NEWSLETTER"),
                            ("EMAIL", "EMAIL"),
                            ("LINKEDIN", "LINKEDIN"),
                            ("INSTAGRAM", "INSTAGRAM"),
                            ("FACEBOOK", "FACEBOOK"),
                            ("X", "X"),
                            ("TIKTOK", "TIKTOK"),
                            ("YOUTUBE", "YOUTUBE"),
                            ("SANDBOX", "SANDBOX"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "identity_vehicle",
                    models.CharField(
                        choices=[
                            ("OWNED_SITE", "OWNED_SITE"),
                            ("NEWSLETTER", "NEWSLETTER"),
                            ("PAGE", "PAGE"),
                            ("PROFILE", "PROFILE"),
                            ("CHANNEL", "CHANNEL"),
                            ("SANDBOX", "SANDBOX"),
                        ],
                        max_length=24,
                    ),
                ),
                ("handle", models.CharField(max_length=180)),
                (
                    "provider_account_id",
                    models.CharField(blank=True, max_length=220, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("active", "active"),
                            ("paused", "paused"),
                            ("quarantined", "quarantined"),
                            ("revoked", "revoked"),
                        ],
                        default=common.enums.AccountStatus["PENDING"],
                        max_length=24,
                    ),
                ),
                (
                    "disclosure_label_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "NOT_REQUIRED"),
                            ("REQUIRED_NOT_SET", "REQUIRED_NOT_SET"),
                            ("SET", "SET"),
                            ("SET_UNVERIFIED", "SET_UNVERIFIED"),
                            ("REVOKED", "REVOKED"),
                        ],
                        default=common.enums.DisclosureLabelStatus["REQUIRED_NOT_SET"],
                        max_length=24,
                    ),
                ),
                ("disclosure_text", models.CharField(blank=True, max_length=280)),
                ("disclosure_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "named_human_admin",
                    models.CharField(
                        blank=True,
                        help_text="Canon §16 (v1.1, A-03): LinkedIn Page traži imenovanog čoveka.",
                        max_length=180,
                    ),
                ),
                (
                    "persona_address",
                    models.CharField(
                        blank=True,
                        help_text="Javna adresa persone; prima poštu.",
                        max_length=320,
                    ),
                ),
                (
                    "sending_domain",
                    models.CharField(
                        blank=True,
                        help_text="Odlazna pošta NIKADA sa primarnog domena kompanije (§12.8).",
                        max_length=253,
                    ),
                ),
                (
                    "dkim_selector",
                    models.CharField(
                        blank=True,
                        help_text="transactional/newsletter/outbound.",
                        max_length=64,
                    ),
                ),
                ("warmup_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_cap",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Ustaljeni plafon 20–50 po mejlboksu (§12.8).",
                        null=True,
                    ),
                ),
                (
                    "credential_ref",
                    models.CharField(
                        blank=True,
                        help_text="Canon §2, §17 — samo referenca na secret store, nikada tajna.",
                        max_length=255,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "channels_account",
            },
        ),
        migrations.CreateModel(
            name="ChannelCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capability", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=32)),
                (
                    "evidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "NONE"),
                            ("RESPONSE_ONLY", "RESPONSE_ONLY"),
                            ("SCREENSHOT", "SCREENSHOT"),
                            ("SCREENSHOT_AND_DOM", "SCREENSHOT_AND_DOM"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("limits_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "channels_capability",
            },
        ),
        migrations.CreateModel(
            name="IntegrationEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "WEBSITE"),
                            ("NEWSLETTER", "NEWSLETTER"),
                            ("EMAIL", "EMAIL"),
                            ("LINKEDIN", "LINKEDIN"),
                            ("INSTAGRAM", "INSTAGRAM"),
                            ("FACEBOOK", "FACEBOOK"),
                            ("X", "X"),
                            ("TIKTOK", "TIKTOK"),
                            ("YOUTUBE", "YOUTUBE"),
                            ("SANDBOX", "SANDBOX"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("base_url", models.TextField(blank=True)),
                ("adapter_key", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("settings_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "channels_integration_endpoint",
            },
        ),
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out")], max_length=8
                    ),
                ),
                ("provider_message_id", models.CharField(max_length=220)),
                ("thread_key", models.CharField(blank=True, max_length=220)),
                ("in_reply_to", models.CharField(blank=True, max_length=220)),
                ("from_addr", models.CharField(max_length=320)),
                ("to_addrs", models.JSONField(blank=True, default=list)),
                ("cc_addrs", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, max_length=998)),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Podleže politici retencije; koverta se čuva uvek.",
                    ),
                ),
                ("body_retained_until", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("dkim_selector", models.CharField(blank=True, max_length=64)),
                (
                    "unsubscribed",
                    models.BooleanField(
                        default=False,
                        help_text="Canon §12.8 tačka 6 — odjava kod jedne persone važi za sve.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Podskup zaglavlja; bez tajni.",
                    ),
                ),
                ("trace_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "channels_mail_message",
            },
        ),
    ]
