# Generated by Django 5.2.17 on 2026-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
        ("runtime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelaccount",
            name="browser_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_accounts",
                to="runtime.browserprofile",
            ),
        ),
        migrations.AddField(
            model_name="channelaccount",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_accounts",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="channelcapability",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capabilities",
                to="channels.channelaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationendpoint",
            constraint=models.UniqueConstraint(
                fields=("channel_type", "name"), name="integration_endpoint_unique"
            ),
        ),
        migrations.AddField(
            model_name="mailmessage",
            name="action",
            field=models.ForeignKey(
                blank=True,
                help_text="Popunjeno za odlaznu poštu — veza sa policy tragom.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mail_messages",
                to="orchestration.action",
            ),
        ),
        migrations.AddField(
            model_name="mailmessage",
            name="channel_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mail_messages",
                to="channels.channelaccount",
            ),
        ),
        migrations.AddField(
            model_name="mailmessage",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mail_messages",
                to="personas.persona",
            ),
        ),
        migrations.AddIndex(
            model_name="channelaccount",
            index=models.Index(
                fields=["persona", "status"], name="channels_ac_persona_1186a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelaccount",
            index=models.Index(
                fields=["channel_type", "disclosure_label_status"],
                name="channels_ac_channel_cb71ff_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_account_id__isnull", False)),
                fields=("channel_type", "provider_account_id"),
                name="channel_account_unique_provider_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelaccount",
            constraint=models.UniqueConstraint(
                fields=("persona", "channel_type", "handle"),
                name="channel_account_unique_handle",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel_type__in", ("TIKTOK", "YOUTUBE")), _negated=True
                ),
                name="channel_account_no_out_of_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("channel_type", "EMAIL"),
                    models.Q(("sending_domain", ""), ("persona_address", "")),
                    _connector="OR",
                ),
                name="channel_account_mail_fields_only_for_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelcapability",
            constraint=models.UniqueConstraint(
                fields=("account", "capability"), name="channel_capability_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="mailmessage",
            index=models.Index(
                fields=["persona", "thread_key"], name="channels_ma_persona_7086d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailmessage",
            index=models.Index(
                fields=["received_at"], name="channels_ma_receive_e55c5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailmessage",
            index=models.Index(
                fields=["sent_at"], name="channels_ma_sent_at_0b28e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailmessage",
            index=models.Index(
                fields=["direction", "created_at"],
                name="channels_ma_directi_06594b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailmessage",
            constraint=models.UniqueConstraint(
                fields=("channel_account", "provider_message_id"),
                name="mail_message_unique_provider_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("direction", "in"), ("received_at__isnull", False)),
                    models.Q(("direction", "out"), ("sent_at__isnull", False)),
                    models.Q(("received_at__isnull", True), ("sent_at__isnull", True)),
                    _connector="OR",
                ),
                name="mail_message_direction_has_timestamp",
            ),
        ),
    ]
