# Generated by Django 5.2.17 on 2026-09-21 08:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppressionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "domain_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNSUBSCRIBE", "UNSUBSCRIBE"),
                            ("COMPLAINT", "COMPLAINT"),
                            ("HARD_BOUNCE", "HARD_BOUNCE"),
                            ("MANUAL", "MANUAL"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="one_click/link/manual/bounce/…", max_length=64
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "db_table": "channels_suppression",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("address_hash", ""), _negated=True),
                        fields=("address_hash",),
                        name="suppression_unique_address",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("address_hash", ""),
                            models.Q(("domain_hash", ""), _negated=True),
                        ),
                        fields=("domain_hash",),
                        name="suppression_unique_domain",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("address_hash", ""), _negated=True),
                            models.Q(("domain_hash", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="suppression_has_target",
                    ),
                ],
            },
        ),
    ]
