# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orchestration", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PERSONA", "PERSONA"),
                            ("REAL_CONTACT", "REAL_CONTACT"),
                            ("ORGANIZATION", "ORGANIZATION"),
                            ("PUBLIC_ENTITY", "PUBLIC_ENTITY"),
                        ],
                        max_length=24,
                    ),
                ),
                ("display_name", models.CharField(max_length=180)),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True,
                        help_text="Ključ za dedupe.",
                        max_length=220,
                        null=True,
                    ),
                ),
                ("is_internal", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "persona",
                    models.OneToOneField(
                        blank=True,
                        help_text="Popunjeno samo za kind=PERSONA.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actor",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "social_graph_actor",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("FOLLOWS", "FOLLOWS"),
                            ("KNOWS", "KNOWS"),
                            ("COLLABORATES", "COLLABORATES"),
                            ("CUSTOMER", "CUSTOMER"),
                            ("PROSPECT", "PROSPECT"),
                            ("COLLEAGUE", "COLLEAGUE"),
                            ("FRIENDLY", "FRIENDLY"),
                            ("BLOCKED", "BLOCKED"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "strength",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "trust",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("muted", "muted"),
                            ("blocked", "blocked"),
                            ("ended", "ended"),
                        ],
                        default=common.enums.RelationshipStatus["ACTIVE"],
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                ("context_json", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="social_graph.actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="social_graph.actor",
                    ),
                ),
            ],
            options={
                "db_table": "social_graph_relationship",
            },
        ),
        migrations.CreateModel(
            name="RelationshipEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=48)),
                (
                    "delta_strength",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "delta_trust",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="social_graph.relationship",
                    ),
                ),
                (
                    "source_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relationship_events",
                        to="orchestration.action",
                    ),
                ),
            ],
            options={
                "db_table": "social_graph_relationship_event",
            },
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(
                fields=["kind", "display_name"], name="social_grap_kind_0c1b41_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("canonical_key__isnull", False)),
                fields=("canonical_key",),
                name="actor_unique_canonical_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "PERSONA"), ("persona__isnull", False)),
                    models.Q(
                        models.Q(("kind", "PERSONA"), _negated=True),
                        ("persona__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="actor_persona_only_for_persona_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["source", "relation_type", "status"],
                name="social_grap_source__5fa4c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["target", "relation_type", "status"],
                name="social_grap_target__32bbd8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "relation_type"),
                name="relationship_unique_triple",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="relationship_no_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("strength__gte", 0), ("strength__lte", 1)),
                name="relationship_strength_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("trust__gte", 0), ("trust__lte", 1)),
                name="relationship_trust_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="relationshipevent",
            index=models.Index(
                fields=["relationship", "occurred_at"],
                name="social_grap_relatio_8b7672_idx",
            ),
        ),
    ]
