# Generated by Django 5.2.17 on 2026-09-18 14:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(max_length=24, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                (
                    "persona_type",
                    models.CharField(
                        choices=[
                            ("AI_CREATOR", "AI_CREATOR"),
                            ("AI_EXPERT", "AI_EXPERT"),
                            ("BRAND_AGENT", "BRAND_AGENT"),
                            ("ASSISTANT", "ASSISTANT"),
                            ("SIMULATION_ONLY", "SIMULATION_ONLY"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("READY", "READY"),
                            ("ACTIVE", "ACTIVE"),
                            ("PAUSED", "PAUSED"),
                            ("DEGRADED", "DEGRADED"),
                            ("SUSPENDED", "SUSPENDED"),
                            ("ARCHIVED", "ARCHIVED"),
                        ],
                        default=common.enums.PersonaStatus["DRAFT"],
                        max_length=24,
                    ),
                ),
                (
                    "runtime_environment",
                    models.CharField(
                        choices=[
                            ("SIMULATION", "SIMULATION"),
                            ("SHADOW", "SHADOW"),
                            ("CONTROLLED_LIVE", "CONTROLLED_LIVE"),
                            ("LIVE", "LIVE"),
                        ],
                        default=common.enums.RuntimeEnvironment["SIMULATION"],
                        max_length=24,
                    ),
                ),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("L0", "L0"),
                            ("L1", "L1"),
                            ("L2", "L2"),
                            ("L3", "L3"),
                            ("L4", "L4"),
                        ],
                        default=common.enums.TrustLevel["L0"],
                        max_length=4,
                    ),
                ),
                (
                    "disclosure_mode",
                    models.CharField(
                        choices=[
                            ("ALWAYS_VISIBLE", "ALWAYS_VISIBLE"),
                            ("PROFILE_ONLY", "PROFILE_ONLY"),
                            ("ON_REQUEST", "ON_REQUEST"),
                        ],
                        max_length=32,
                    ),
                ),
                ("disclosure_required", models.BooleanField(default=True)),
                ("primary_locale", models.CharField(max_length=16)),
                ("timezone", models.CharField(max_length=64)),
                (
                    "birth_date_model",
                    models.DateField(
                        blank=True,
                        help_text="Modelovana starost; nije državni identitet.",
                        null=True,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "config_ext",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canon §5, *_ext obrazac: polja iz Persona Spec-a koja nemaju kolonu. JSONB bez JSON Scheme nije dozvoljen.",
                    ),
                ),
            ],
            options={
                "db_table": "personas_persona",
            },
        ),
        migrations.CreateModel(
            name="IdentityFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("namespace", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=120)),
                ("value_json", models.JSONField(blank=True, default=dict)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("user_provided", "user_provided"),
                            ("generated", "generated"),
                            ("inferred", "inferred"),
                        ],
                        default=common.enums.Provenance["USER_PROVIDED"],
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("priority", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "personas_identity_fact",
            },
        ),
        migrations.CreateModel(
            name="LifeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("year", models.SmallIntegerField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=48)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField()),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("user_provided", "user_provided"),
                            ("generated", "generated"),
                            ("inferred", "inferred"),
                        ],
                        default=common.enums.Provenance["USER_PROVIDED"],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "db_table": "personas_life_event",
            },
        ),
        migrations.CreateModel(
            name="PersonaAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias_type", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=160)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "personas_alias",
            },
        ),
        migrations.CreateModel(
            name="PersonaTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("category", models.CharField(max_length=40)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "personas_tag",
            },
        ),
        migrations.CreateModel(
            name="PersonaTagLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("source", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "personas_tag_link",
            },
        ),
        migrations.CreateModel(
            name="Biography",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="biography",
                        serialize=False,
                        to="personas.persona",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=220)),
                ("short_bio", models.TextField()),
                ("long_bio", models.TextField()),
                ("occupation_title", models.CharField(blank=True, max_length=160)),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("education_summary", models.TextField(blank=True)),
                (
                    "location_label",
                    models.CharField(
                        blank=True,
                        help_text="Modelovana lokacija, ne tačna adresa.",
                        max_length=160,
                    ),
                ),
                ("values_json", models.JSONField(blank=True, default=list)),
                ("story_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "personas_biography",
            },
        ),
        migrations.CreateModel(
            name="TraitProfile",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="trait_profile",
                        serialize=False,
                        to="personas.persona",
                    ),
                ),
                (
                    "openness",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "conscientiousness",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "extraversion",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "agreeableness",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "emotional_stability",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "curiosity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Trajna dispozicija; trenutna vrednost je BehaviourState.curiosity_now.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "humor",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "formality",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "risk_tolerance",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "commercial_intensity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "contrarian",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "evidence_preference",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "traits_ext",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canon §5 — uz JSON Schema validaciju.",
                    ),
                ),
                ("trait_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "personas_trait_profile",
            },
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="voice_profile",
                        serialize=False,
                        to="personas.persona",
                    ),
                ),
                ("tone", models.CharField(max_length=120)),
                ("register", models.CharField(max_length=64)),
                (
                    "verbosity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Canon §5: stil, ne osobina.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "sentence_length_bias",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.5,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("emoji_allowed", models.BooleanField(default=False)),
                ("hashtag_max", models.SmallIntegerField(default=0)),
                ("reading_level", models.SmallIntegerField(blank=True, null=True)),
                ("signature_phrases", models.JSONField(blank=True, default=list)),
                ("banned_phrases", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "style_ext",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canon §5 — uz JSON Schema validaciju.",
                    ),
                ),
                ("voice_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "personas_voice_profile",
            },
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(
                fields=["status", "persona_type"], name="personas_pe_status_064389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(
                fields=["disclosure_mode"], name="personas_pe_disclos_217388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="persona",
            index=models.Index(
                fields=["runtime_environment", "status"],
                name="personas_pe_runtime_c79528_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ARCHIVED"), _negated=True),
                    ("archived_at__isnull", False),
                    _connector="OR",
                ),
                name="persona_archived_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.CheckConstraint(
                condition=models.Q(("trust_level__in", ("L0", "L1", "L2"))),
                name="persona_trust_level_assignable",
            ),
        ),
        migrations.AddField(
            model_name="identityfact",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_facts",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="lifeevent",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_events",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="personaalias",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="personas.persona",
            ),
        ),
        migrations.AddIndex(
            model_name="personatag",
            index=models.Index(
                fields=["category", "slug"], name="personas_ta_categor_a38586_idx"
            ),
        ),
        migrations.AddField(
            model_name="personataglink",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_links",
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="personataglink",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persona_links",
                to="personas.personatag",
            ),
        ),
        migrations.AddIndex(
            model_name="biography",
            index=models.Index(
                fields=["occupation_title"], name="personas_bi_occupat_33d29b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biography",
            index=models.Index(
                fields=["industry"], name="personas_bi_industr_4caf72_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("openness__gte", 0), ("openness__lte", 1)),
                name="trait_openness_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conscientiousness__gte", 0), ("conscientiousness__lte", 1)
                ),
                name="trait_conscientiousness_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("extraversion__gte", 0), ("extraversion__lte", 1)),
                name="trait_extraversion_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("agreeableness__gte", 0), ("agreeableness__lte", 1)
                ),
                name="trait_agreeableness_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("emotional_stability__gte", 0), ("emotional_stability__lte", 1)
                ),
                name="trait_emotional_stability_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("curiosity__gte", 0), ("curiosity__lte", 1)),
                name="trait_curiosity_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("humor__gte", 0), ("humor__lte", 1)),
                name="trait_humor_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("formality__gte", 0), ("formality__lte", 1)),
                name="trait_formality_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("risk_tolerance__gte", 0), ("risk_tolerance__lte", 1)
                ),
                name="trait_risk_tolerance_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commercial_intensity__gte", 0), ("commercial_intensity__lte", 1)
                ),
                name="trait_commercial_intensity_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("contrarian__gte", 0), ("contrarian__lte", 1)),
                name="trait_contrarian_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("evidence_preference__gte", 0), ("evidence_preference__lte", 1)
                ),
                name="trait_evidence_preference_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("verbosity__gte", 0), ("verbosity__lte", 1)),
                name="voice_verbosity_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sentence_length_bias__gte", 0), ("sentence_length_bias__lte", 1)
                ),
                name="voice_sentence_length_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("hashtag_max__gte", 0), ("hashtag_max__lte", 30)),
                name="voice_hashtag_max_range",
            ),
        ),
        migrations.AddIndex(
            model_name="identityfact",
            index=models.Index(
                fields=["persona", "namespace", "key"],
                name="personas_id_persona_5b740e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="identityfact",
            constraint=models.UniqueConstraint(
                fields=("persona", "namespace", "key", "valid_from"),
                name="identity_fact_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="lifeevent",
            index=models.Index(
                fields=["persona", "event_date"], name="personas_li_persona_a53d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lifeevent",
            index=models.Index(
                fields=["persona", "event_type"], name="personas_li_persona_2ffbf0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lifeevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="life_event_confidence_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="personaalias",
            constraint=models.UniqueConstraint(
                fields=("persona", "alias_type", "value"), name="alias_unique_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="personaalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("persona", "alias_type"),
                name="alias_one_primary_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="personataglink",
            constraint=models.UniqueConstraint(
                fields=("persona", "tag"), name="tag_link_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="personataglink",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0), ("weight__lte", 1)),
                name="tag_link_weight_unit",
            ),
        ),
    ]
