# Generated by Django 5.2.17 on 2026-09-23 09:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import common.enums


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("purpose", models.TextField(blank=True)),
                (
                    "human_owner",
                    models.CharField(
                        blank=True,
                        help_text="Čovek koji odgovara za sektor (user:…).",
                        max_length=120,
                    ),
                ),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent koji vodi sektor; odgovornost čoveka time ne prestaje.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heads_departments",
                        to="personas.persona",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="personas.department",
                    ),
                ),
            ],
            options={
                "db_table": "personas_department",
            },
        ),
        migrations.CreateModel(
            name="PersonaDossier",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dossier",
                        serialize=False,
                        to="personas.persona",
                    ),
                ),
                ("birth_place", models.CharField(blank=True, max_length=120)),
                ("residence", models.CharField(blank=True, max_length=160)),
                ("height_cm", models.SmallIntegerField(blank=True, null=True)),
                ("weight_kg", models.SmallIntegerField(blank=True, null=True)),
                ("build", models.CharField(blank=True, max_length=48)),
                ("eye_color", models.CharField(blank=True, max_length=32)),
                ("hair_color", models.CharField(blank=True, max_length=32)),
                ("hair_style", models.CharField(blank=True, max_length=64)),
                ("distinguishing_marks", models.CharField(blank=True, max_length=200)),
                ("marital_status", models.CharField(blank=True, max_length=48)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("hobbies", models.JSONField(blank=True, default=list)),
                (
                    "appearance_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Opis za generisanje slike; isti lik na svakoj slici.",
                    ),
                ),
                ("dossier_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "personas_dossier",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("height_cm__isnull", True),
                            models.Q(("height_cm__gte", 120), ("height_cm__lte", 230)),
                            _connector="OR",
                        ),
                        name="dossier_height_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weight_kg__isnull", True),
                            models.Q(("weight_kg__gte", 35), ("weight_kg__lte", 250)),
                            _connector="OR",
                        ),
                        name="dossier_weight_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("specialty", models.CharField(blank=True, max_length=160)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("head", "head"),
                            ("lead", "lead"),
                            ("senior", "senior"),
                            ("medior", "medior"),
                            ("junior", "junior"),
                        ],
                        default=common.enums.OrgLevel["MEDIOR"],
                        max_length=16,
                    ),
                ),
                (
                    "duties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Šta radi, jednom rečenicom po stavci.",
                    ),
                ),
                ("headcount_max", models.PositiveSmallIntegerField(default=1)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="personas.department",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="personas.position",
                    ),
                ),
            ],
            options={
                "db_table": "personas_position",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="personas.persona",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="personas.position",
                    ),
                ),
            ],
            options={
                "db_table": "personas_assignment",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="personas_de_is_acti_7bb263_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["department", "level"], name="personas_po_departm_0f0a29_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.CheckConstraint(
                condition=models.Q(("headcount_max__gte", 1)),
                name="position_headcount_min_one",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["persona", "ended_at"], name="personas_as_persona_0ed335_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True), ("is_primary", True)),
                fields=("persona",),
                name="assignment_one_primary_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("ended_at__gt", models.F("started_at")),
                    _connector="OR",
                ),
                name="assignment_end_after_start",
            ),
        ),
    ]
