# Generated by Django 5.2.17 on 2026-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0002_f11_org_and_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="needs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Šta posao traži da bi se radio — opis, ne dozvola.",
            ),
        ),
    ]
