# Generated by Django 5.2.17 on 2026-10-01 05:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0003_adr_0037_position_needs"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionHandbookRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Stabilan ključ pravila — po njemu se pravilo gasi i ponovo upisuje.",
                        max_length=48,
                    ),
                ),
                (
                    "sort_order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Redosled u promptu. Pravila se čitaju kao spisak, ne skup.",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Pravilo, kako ga model čita. Jedna misao po pravilu.",
                        max_length=400,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Odakle je pravilo: broj ADR-a, glava priručnika, zadatak. Čuva se uvek; u prompt ne ulazi (ADR-0060 §3).",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "retired_reason",
                    models.CharField(
                        blank=True,
                        help_text="Zašto je pravilo ugašeno. Ugašeno bez razloga se ne upisuje.",
                        max_length=300,
                    ),
                ),
                ("created_by", models.CharField(max_length=120)),
                ("retired_by", models.CharField(blank=True, max_length=120)),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Radno mesto čiji je ovo priručnik (`RAZ-PRO`, `IST-ANA`, …).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handbook_rules",
                        to="personas.position",
                    ),
                ),
            ],
            options={
                "db_table": "personas_position_handbook_rule",
                "indexes": [
                    models.Index(
                        fields=["position", "is_active", "sort_order"],
                        name="personas_po_positio_650fe5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "key"),
                        name="handbook_rule_key_per_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", ""), _negated=True),
                        name="handbook_rule_source_required",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_active", True),
                            models.Q(
                                models.Q(("retired_reason", ""), _negated=True),
                                models.Q(("retired_by", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="handbook_rule_retired_has_reason",
                    ),
                ],
            },
        ),
    ]
